-- ============================================================================
-- ✅ APLICADA el 11/08/2026. Verificada en las dos direcciones (ver el final).
--
-- EL CONTENIDO DE LA COMUNIDAD SE LEE SIN INICIAR SESIÓN  (detectado 10/08/2026)
--
-- Comprobado contra producción con la clave pública —que está en el
-- repositorio, que es público— y sin ninguna sesión:
--
--   GET /rest/v1/help_posts_feed?select=preview,user_name,anon
--   → 200 OK, devuelve los pedidos de la Sala de Ayuda
--
-- Lo mismo con `bitacora_posts_full` y `happy_posts_full`. Es decir: cualquiera
-- puede descargar todo lo que la gente escribió en la Sala de Ayuda, la
-- Bitácora y el Muro, sin tener cuenta.
--
-- QUÉ **NO** ES: no es una de-anonimización. El arreglo del 29/07 sigue en pie
-- y se verificó en la misma prueba — las publicaciones anónimas salen con
-- `user_name: "Usuario Anónimo"` y sin identificador. La identidad está a salvo.
--
-- QUÉ SÍ ES: el contenido queda expuesto más allá de lo que la app da a
-- entender. La Política de Privacidad describe el contenido comunitario como
-- compartido «entre usuarios», y la Sala de Ayuda es, por definición, gente
-- contando por qué necesita ayuda. Que sea descargable por cualquiera no
-- encaja con eso. En las publicaciones NO anónimas se expone además el nombre
-- que la persona eligió mostrar.
--
-- Los grants a `anon` vienen de las migraciones de julio (20260717b, 20260718f,
-- 20260718h). En su momento fue deliberado para no romper nada; no se revisó
-- después si seguía siendo necesario.
--
-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️ POR QUÉ NO SE APLICÓ, Y QUÉ HAY QUE HACER ANTES
--
-- `pRenderHelp`, `_btLoadTab` y `pRenderHappy` **NO llaman a
-- `_ensureSbSession()` antes de leer**. Al abrir la app en frío, si la sesión
-- de Supabase todavía no se restauró, esas lecturas salen como `anon`.
--
-- Hoy funcionan porque las vistas están abiertas a `anon`. Si se cierran sin
-- tocar el cliente, **los tres feeds aparecerán vacíos al arrancar** hasta que
-- la sesión termine de restaurarse. Sería un fallo visible para todo el mundo.
--
-- ORDEN CORRECTO:
--   1. ✅ HECHO en v1630. `pRenderHelp`, `_btLoadTab` y `pRenderHappy` esperan
--      ahora a `_sessionReady()` antes de su primera lectura. La espera se hace
--      una sola vez por carga; el render desde caché sigue siendo inmediato.
--   2. ✅ 11/08. En lugar del arranque en frío en el teléfono —que no se puede
--      hacer desde acá— se comprobó contra la base simulando exactamente lo que
--      hace PostgREST con cada rol (`set local role` + `request.jwt.claims`).
--      Antes de aplicar: anon 22/3/10 y authenticated 22/3/10.
--      Después:          anon BLOQUEADO y authenticated 22/3/10 — sin cambios.
--   3. ✅ Aplicada.
--   4. ✅ Verificada también por HTTP con la clave pública: las tres vistas
--      devuelven 401 `permission denied` sin sesión.
--
-- QUEDA UNA COMPROBACIÓN QUE SÓLO SE PUEDE HACER EN EL TELÉFONO: que en un
-- arranque en frío la sesión se restaure antes de la primera lectura. Si algún
-- feed apareciera vacío al abrir la app, se revierte en un segundo con:
--   grant select on public.help_posts_feed, public.bitacora_posts_full,
--                    public.happy_posts_full to anon;
-- ══════════════════════════════════════════════════════════════════════════

revoke select on public.help_posts_feed     from anon;
revoke select on public.bitacora_posts_full from anon;
revoke select on public.happy_posts_full    from anon;

-- Se dejan accesibles a `anon` a propósito:
--   * `bitacora_reported_ids` — sólo ids, sin contenido ni autor.
--   * `daily_responses_feed`, `dq_comments_feed`, `momento_comments_feed`,
--     `bitacora_comments_full` — revisar con el mismo criterio en su momento;
--     no se tocan acá para no ampliar el alcance de un cambio ya delicado.

-- ── VERIFICACIÓN (tras aplicar) ────────────────────────────────────────────
-- Sin sesión, con la clave pública, las tres deben dar 0 filas:
--   curl -s "$SUPA/rest/v1/help_posts_feed?select=id&limit=1" -H "apikey: $ANON"
--   curl -s "$SUPA/rest/v1/bitacora_posts_full?select=id&limit=1" -H "apikey: $ANON"
--   curl -s "$SUPA/rest/v1/happy_posts_full?select=id&limit=1" -H "apikey: $ANON"
--
-- Y con sesión, los feeds tienen que seguir completos.
