-- Una función que escribe el DDL completo del esquema `public`.
--
-- POR QUÉ EXISTE
-- Las copias de seguridad nocturnas guardan los DATOS (backup.js → artefacto),
-- pero no la ESTRUCTURA. Y 27 de las 61 tablas —entre ellas `profiles`,
-- `momentos`, `circles`, `daily_responses`, `reviews`— nunca tuvieron un
-- `create table` en el repositorio: se hicieron a mano en el panel de Supabase.
--
-- O sea que, si se perdiera el proyecto, había 1231 filas de diarios, ánimos y
-- conversaciones sin ningún sitio donde volcarlas. Habría que deducir la
-- estructura a partir del JSON, con las policies, los índices y los triggers
-- perdidos. Una copia de datos sin esquema no es una copia: es un rompecabezas.
--
-- El plan gratuito de Supabase no da `pg_dump`, así que el volcado se genera
-- desde dentro de la base. El workflow lo llama cada noche y guarda el
-- resultado en `supabase/schema.sql`, dentro del repositorio. El DDL no lleva
-- datos personales, así que puede vivir en git; los datos no, y siguen yendo a
-- un artefacto privado.
--
-- El orden importa y es el de una restauración real: tablas → restricciones →
-- funciones → vistas → índices → triggers → RLS → permisos. Las vistas y las
-- policies llaman a funciones (velo_is_admin, velo_is_premium), por eso las
-- funciones van antes.
--
-- Que esto sea CORRECTO no se afirma: se comprueba. El workflow
-- «Prueba de restauración» levanta un PostgreSQL vacío, le aplica este volcado
-- y le mete encima la copia de datos de esa misma noche. Si el volcado se
-- queda corto, la prueba falla y llega el aviso.

create or replace function public.velo_dump_schema()
returns text
language plpgsql
security definer
set search_path to 'public', 'pg_catalog'
as $fn$
declare
  out_text text := '';
  r record;
begin
  out_text := out_text ||
    '-- Esquema de Velo (schema public). GENERADO AUTOMÁTICAMENTE.' || E'\n' ||
    '-- No editar a mano: lo reescribe el workflow "Copia de seguridad de la base"' || E'\n' ||
    '-- llamando a public.velo_dump_schema(). Para cambiar la base, escribí una' || E'\n' ||
    '-- migración en supabase/migrations/ y este archivo se actualizará solo.' || E'\n\n' ||
    'create extension if not exists pgcrypto;' || E'\n\n';

  -- ── 1. Tablas ────────────────────────────────────────────────────────────
  out_text := out_text || '-- ══ TABLAS ══' || E'\n\n';
  for r in
    select c.oid, c.relname
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r'
    order by c.relname
  loop
    out_text := out_text || 'create table if not exists public.' || quote_ident(r.relname) || ' (' || E'\n';
    out_text := out_text || (
      select string_agg(
        '  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
        || case when a.attidentity = 'a' then ' generated always as identity'
                when a.attidentity = 'd' then ' generated by default as identity'
                else '' end
        || case when a.attgenerated = 's'
                then ' generated always as (' || pg_get_expr(ad.adbin, ad.adrelid) || ') stored'
                when ad.adbin is not null and a.attidentity = ''
                then ' default ' || pg_get_expr(ad.adbin, ad.adrelid)
                else '' end
        || case when a.attnotnull then ' not null' else '' end,
        ',' || E'\n' order by a.attnum)
      from pg_attribute a
      left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
      where a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped
    ) || E'\n);\n\n';
  end loop;

  -- ── 2. Restricciones (después de TODAS las tablas, por las claves ajenas) ─
  out_text := out_text || '-- ══ RESTRICCIONES ══' || E'\n\n';
  for r in
    select c.relname as tabla, con.conname, pg_get_constraintdef(con.oid) as def, con.contype
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
    order by case con.contype when 'p' then 1 when 'u' then 2 when 'c' then 3 else 4 end,
             c.relname, con.conname
  loop
    out_text := out_text ||
      'alter table public.' || quote_ident(r.tabla) ||
      ' drop constraint if exists ' || quote_ident(r.conname) || ';' || E'\n' ||
      'alter table public.' || quote_ident(r.tabla) ||
      ' add constraint ' || quote_ident(r.conname) || ' ' || r.def || ';' || E'\n';
  end loop;
  out_text := out_text || E'\n';

  -- ── 3. Funciones (las vistas y las policies las necesitan) ───────────────
  out_text := out_text || '-- ══ FUNCIONES ══' || E'\n\n';
  for r in
    select pg_get_functiondef(p.oid) as def
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    left join pg_depend d on d.objid = p.oid and d.deptype = 'e'
    where n.nspname = 'public' and p.prokind in ('f','p') and d.objid is null
    order by p.proname
  loop
    out_text := out_text || r.def || ';' || E'\n\n';
  end loop;

  -- ── 4. Vistas (con security_invoker si lo tienen) ────────────────────────
  out_text := out_text || '-- ══ VISTAS ══' || E'\n\n';
  for r in
    select c.relname,
           pg_get_viewdef(c.oid, true) as def,
           coalesce((select option_value from pg_options_to_table(c.reloptions)
                      where option_name = 'security_invoker'), '') as inv
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'v'
    order by c.relname
  loop
    out_text := out_text || 'create or replace view public.' || quote_ident(r.relname) ||
      case when r.inv <> '' then ' with (security_invoker=' || r.inv || ')' else '' end ||
      ' as' || E'\n' || r.def || E'\n\n';
  end loop;

  -- ── 5. Índices (los de las restricciones ya fueron) ──────────────────────
  out_text := out_text || '-- ══ ÍNDICES ══' || E'\n\n';
  for r in
    select i.indexdef
    from pg_indexes i
    where i.schemaname = 'public'
      and not exists (
        select 1 from pg_constraint con
        join pg_class ic on ic.oid = con.conindid
        where ic.relname = i.indexname)
    order by i.tablename, i.indexname
  loop
    out_text := out_text || replace(r.indexdef, 'CREATE INDEX', 'CREATE INDEX IF NOT EXISTS') || ';' || E'\n';
  end loop;
  out_text := out_text || E'\n';

  -- ── 6. Triggers ──────────────────────────────────────────────────────────
  out_text := out_text || '-- ══ TRIGGERS ══' || E'\n\n';
  for r in
    select c.relname as tabla, t.tgname, pg_get_triggerdef(t.oid) as def
    from pg_trigger t
    join pg_class c on c.oid = t.tgrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and not t.tgisinternal
    order by c.relname, t.tgname
  loop
    out_text := out_text ||
      'drop trigger if exists ' || quote_ident(r.tgname) || ' on public.' || quote_ident(r.tabla) || ';' || E'\n' ||
      r.def || ';' || E'\n';
  end loop;
  out_text := out_text || E'\n';

  -- ── 7. RLS y policies ────────────────────────────────────────────────────
  out_text := out_text || '-- ══ SEGURIDAD A NIVEL DE FILA ══' || E'\n\n';
  for r in
    select c.relname, c.relrowsecurity, c.relforcerowsecurity
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r'
    order by c.relname
  loop
    if r.relrowsecurity then
      out_text := out_text || 'alter table public.' || quote_ident(r.relname) || ' enable row level security;' || E'\n';
    end if;
    if r.relforcerowsecurity then
      out_text := out_text || 'alter table public.' || quote_ident(r.relname) || ' force row level security;' || E'\n';
    end if;
  end loop;
  out_text := out_text || E'\n';

  for r in
    select p.tablename, p.policyname, p.permissive, p.roles, p.cmd, p.qual, p.with_check
    from pg_policies p where p.schemaname = 'public'
    order by p.tablename, p.policyname
  loop
    out_text := out_text ||
      'drop policy if exists ' || quote_ident(r.policyname) || ' on public.' || quote_ident(r.tablename) || ';' || E'\n' ||
      'create policy ' || quote_ident(r.policyname) || ' on public.' || quote_ident(r.tablename) ||
      ' as ' || r.permissive ||
      ' for ' || case r.cmd when 'ALL' then 'all' else lower(r.cmd) end ||
      ' to ' || array_to_string(r.roles, ', ') ||
      coalesce(' using (' || r.qual || ')', '') ||
      coalesce(' with check (' || r.with_check || ')', '') || ';' || E'\n';
  end loop;
  out_text := out_text || E'\n';

  -- ── 8. Permisos ──────────────────────────────────────────────────────────
  out_text := out_text || '-- ══ PERMISOS ══' || E'\n\n';
  for r in
    select g.table_name, g.grantee, string_agg(distinct g.privilege_type, ', ') as privs
    from information_schema.role_table_grants g
    where g.table_schema = 'public' and g.grantee in ('anon','authenticated','service_role')
    group by g.table_name, g.grantee
    order by g.table_name, g.grantee
  loop
    out_text := out_text || 'grant ' || r.privs || ' on public.' || quote_ident(r.table_name) ||
                ' to ' || quote_ident(r.grantee) || ';' || E'\n';
  end loop;
  out_text := out_text || E'\n';

  for r in
    select p.proname, pg_get_function_identity_arguments(p.oid) as args, g.grantee
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    cross join lateral (values ('anon'),('authenticated'),('service_role')) as g(grantee)
    left join pg_depend d on d.objid = p.oid and d.deptype = 'e'
    where n.nspname = 'public' and p.prokind in ('f','p') and d.objid is null
      and has_function_privilege(g.grantee, p.oid, 'EXECUTE')
    order by p.proname, g.grantee
  loop
    out_text := out_text || 'grant execute on function public.' || quote_ident(r.proname) ||
                '(' || r.args || ') to ' || quote_ident(r.grantee) || ';' || E'\n';
  end loop;

  -- Lo que NO se concede es tan importante como lo que sí: si una función se
  -- restauró con el EXECUTE que Postgres da a PUBLIC por defecto, queda abierta
  -- a anónimos aunque arriba no figure (ver HANDOVER §12).
  out_text := out_text || E'\n' ||
    '-- Las funciones nacen con EXECUTE concedido a PUBLIC. Se lo quitamos a todas' || E'\n' ||
    '-- y arriba quedó escrito, una por una, quién lo recupera.' || E'\n';
  for r in
    select p.proname, pg_get_function_identity_arguments(p.oid) as args
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    left join pg_depend d on d.objid = p.oid and d.deptype = 'e'
    where n.nspname = 'public' and p.prokind in ('f','p') and d.objid is null
      and not has_function_privilege('anon', p.oid, 'EXECUTE')
    order by p.proname
  loop
    out_text := out_text || 'revoke execute on function public.' || quote_ident(r.proname) ||
                '(' || r.args || ') from public;' || E'\n';
  end loop;

  return out_text;
end $fn$;

-- Sólo el servidor. Un volcado del esquema le dice a cualquiera dónde mirar.
revoke execute on function public.velo_dump_schema() from public;
revoke execute on function public.velo_dump_schema() from anon;
revoke execute on function public.velo_dump_schema() from authenticated;
grant  execute on function public.velo_dump_schema() to service_role;

-- ─────────────────────────────────────────────────────────────────────────────
-- Y la lista de cuentas, que faltaba en las copias.
--
-- Cinco tablas apuntan con clave ajena a auth.users(id): mood_entries,
-- diary_entries, daily_responses, dq_reactions y content_reports. O sea: los
-- ánimos, los diarios y las respuestas diarias. PostgREST no expone auth.users,
-- así que backup.js nunca la guardó — y sin ella esas filas no entran en una
-- base recién creada. La restauración se detenía justo en los datos más
-- personales, y nadie lo sabía porque nunca se había probado.
--
-- Se copian id, email y fechas: lo justo para volver a crear las cuentas y
-- reenlazar los datos. NO se copia `encrypted_password`. Guardar hashes de
-- contraseña en un artefacto de GitHub es una decisión del titular, no algo que
-- se hace de oficio; sin ellos, al restaurar hay que pedirle a cada persona que
-- vuelva a entrar con su correo (queda anotado en PENDIENTE-DEL-TITULAR.md).

create or replace function public.velo_dump_auth_users()
returns json
language sql
security definer
set search_path to 'auth', 'pg_catalog'
as $$
  select coalesce(json_agg(json_build_object(
    'id', u.id,
    'email', u.email,
    'created_at', u.created_at,
    'last_sign_in_at', u.last_sign_in_at,
    'email_confirmed_at', u.email_confirmed_at
  ) order by u.created_at), '[]'::json)
  from auth.users u;
$$;

revoke execute on function public.velo_dump_auth_users() from public;
revoke execute on function public.velo_dump_auth_users() from anon;
revoke execute on function public.velo_dump_auth_users() from authenticated;
grant  execute on function public.velo_dump_auth_users() to service_role;
