-- Lo que encontró la prueba de restauración en su primera ejecución útil.
--
-- Son dos cosas, y las dos son exactamente lo que un simulacro contra la base
-- viva no podía ver: allí las tablas ya existían y nadie intentaba reinsertar
-- ninguna fila.
--
-- ── 1. Nueve tablas no admitían sus propios ids ────────────────────────────
-- Su columna `id` era GENERATED ALWAYS AS IDENTITY, que quiere decir
-- literalmente «nadie escribe acá, ni siquiera con un valor válido»:
--
--   ERROR: cannot insert a non-DEFAULT value into column "id"
--   HINT:  Use OVERRIDING SYSTEM VALUE to override.
--
-- Al restaurar hay que devolver los ids que había, porque otras filas apuntan a
-- ellos. En SQL se puede sortear con OVERRIDING SYSTEM VALUE, pero la
-- restauración de verdad (restore.js) va por PostgREST, que no ofrece esa
-- cláusula. Por ahí no había forma.
--
-- GENERATED BY DEFAULT hace lo mismo cuando no le pasás valor —sigue numerando
-- sola— y además acepta uno explícito. Para el uso normal no cambia nada.
--
-- ── 2. El volcado no incluía las secuencias ────────────────────────────────
-- `circle_messages.id` es un serial a la vieja usanza:
--   id bigint default nextval('circle_messages_id_seq'::regclass)
--
-- Sin el `create sequence`, la tabla no se crea:
--   ERROR: relation "public.circle_messages" does not exist
-- ...y detrás se caen sus restricciones, sus policies y sus permisos. Los
-- mensajes de los Círculos de Paz no se restauraban.
--
-- Dos detalles que costaron dos intentos, anotados para el próximo:
--
--   · Las secuencias de una columna `identity` NO hay que crearlas: las crea su
--     tabla, con el mismo nombre. Crearlas antes da «relation already exists» y
--     tira abajo nueve tablas. Se distinguen por `pg_depend.deptype`: 'i' las de
--     identity, 'a' las de un serial clásico.
--   · `pg_sequence_last_value()` revienta si le pasás un índice, y PostgreSQL no
--     promete evaluar el WHERE antes que las funciones del SELECT. Daba
--     «cannot open relation saml_providers_pkey», un índice de otro esquema que
--     el WHERE ya descartaba. Hace falta `offset 0` como barrera de
--     optimización para obligarlo a filtrar primero.

alter table public.bot_attempts     alter column id set generated by default;
alter table public.data_requests    alter column id set generated by default;
alter table public.deleted_accounts alter column id set generated by default;
alter table public.ia_usage         alter column id set generated by default;
alter table public.news_reactions   alter column id set generated by default;
alter table public.push_history     alter column id set generated by default;
alter table public.quote_reactions  alter column id set generated by default;
alter table public.usage_events     alter column id set generated by default;
alter table public.velo_api_usage   alter column id set generated by default;

-- Las funciones del volcado (velo_dump_sequences, velo_dump_schema_partes y el
-- envoltorio velo_dump_schema) quedan en la base y se reflejan solas en
-- supabase/schema.sql, que las incluye en su sección de FUNCIONES. Se aplicaron
-- con las migraciones `volcado_secuencias_con_barrera` y `volcado_esquema_partes`.
